### ISSUE TITLE
code and sdk library mismatch 

### ISSUE THREAD

**Issue by brabo-hi** [lightsparkdev/kotlin-sdk#32]
I am currently using `com.lightspark:lightspark-sdk:0.3.0` and `com.lightspark:wallet-sdk:0.1.2`

It looks like there is a version conflict between the `core-jvm` and `sdk-jvm`
Here is the complete stacktrace
```
Execution failed for task ':run'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.chrynan.krypt:krypt-csprng:0.3.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/chrynan/krypt/krypt-csprng/0.3.1/krypt-csprng-0.3.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > com.lightspark:lightspark-sdk:0.3.0 > com.lightspark:lightspark-sdk-jvm:0.3.0 > com.lightspark:lightspark-core:0.3.1 > com.lightspark:lightspark-core-jvm:0.3.1
```

**Comment by jklein24** [comment]
Hey @brabo-hi, I'm sorry I missed this issue previously! It looks like you may just need to add the repository for krypt to your repository list. Something like:

```
repositories {
      google()
      mavenCentral()
      maven { url = uri("https://repo.repsy.io/mvn/chrynan/public") }
  }
```

if you're using kotlin gradle files. Let me know if that doesn't work!

**Comment by brabo-hi** [comment]
@jklein24  it looks like `com.lightspark.sdk.auth.AccountTokenAuthProvider` is not defined into the library `com.lightspark:lightspark-sdk:0.3.0`

**Comment by jklein24** [comment]
Hi @brabo-hi it looks like it's actually AuthProvider that's throwing that error. It seems like you probably just need to add a dependency on `com.lightspark:lightspark-core:0.3.1`.

**Comment by jklein24** [comment]
Closing out this issue as complete, but please let us know if you run into other issues during testing!
